language: cpp
addons:
  apt:
    packages:
      - libboost-system-dev
      - libboost-coroutine-dev
  homebrew:
    packages:
      - boost
    update: false
os:
  - linux
  - windows
  - osx
dist: focal
env:
- HOMEBREW_NO_AUTO_UPDATE=1
osx_image: xcode12.5
before_install:
  - OPTS=""
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install conan boost-msvc-14.1; export PATH=$(cmd.exe //c "refreshenv > nul & C:\Progra~1\Git\bin\bash -c 'echo \$PATH' "); OPTS="-A x64"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip3 install --user conan; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH=$PATH:$(python3 -m site --user-base)/bin; python3 -m pip install --user conan; fi

script:
  - mkdir -p build
  - cd build
  - cmake .. $OPTS
  - cmake --build .
  - ctest
